---
version: "3.8"

x-spark-common:
  &spark-common
  image: spark-base:3.3.1
  # build:
  #   context: .
  #   dockerfile: base.Dockerfile
  networks:
    - main-network
  env_file:
    - ./spark.env
    - ./hadoop.env
  volumes:
    - &spark-common-volumes-logs
      type: volume
      source: spark-volume
      target: /tmp/logs
  restart: always

x-spark-worker-common:
  &spark-worker-common
  <<: *spark-common
  command: worker
  ports:
    # SPARK_WORKER_WEBUI_PORT
    - target: 8081
      published: 8081
      mode: host
  environment:
    &spark-worker-common-environment
    SERVICE_PRECONDITION: "spark-master:7077"
  depends_on:
    - spark-master


services:

  spark-master:
    <<: *spark-common
    # SPARK_MASTER_HOST
    container_name: spark-master
    command: master
    ports:
      # SPARK_MASTER_WEBUI_PORT
      - target: 8080
        published: 8090
        mode: host
      # SPARK_MASTER_PORT
      - target: 7077
        published: 7077
        mode: host
    volumes:
      - *spark-common-volumes-logs
      - type: bind
        source: ./data
        target: /workspace
  
  spark-worker-1:
    <<: *spark-worker-common
    container_name: spark-worker-1
    environment:
      <<: *spark-worker-common-environment
      SPARK_WORKER_PORT: 38112
      SPARK_WORKER_WEBUI_PORT: 8081

  spark-historyserver:
    <<: *spark-common
    container_name: spark-historyserver
    command: historyserver
    ports:
      # SPARK_HISTORY_SERVER_WEBUI_PORT
      - target: 18080
        published: 18080
        mode: host
    environment:
      SERVICE_PRECONDITION: "spark-master:7077 spark-worker-1:38112"
    depends_on:
      - spark-master
      - spark-worker-1

  spark-thriftserver:
    <<: *spark-common
    container_name: spark-thriftserver
    command: thriftserver
    ports:
      - target: 10000
        published: 10000
        mode: host
    environment:
      SERVICE_PRECONDITION: "spark-master:7077"
    depends_on:
      - spark-master


networks:
  main-network:
    name: main-network
    external: false
    driver: bridge
    attachable: false


volumes:
  spark-volume:
